services:
  auth_management:
    build: ./AuthManagement
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - server.port=8080
      - server.address=0.0.0.0

  user-management:
    build: ./UserManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_user_db:3306/user_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
      - server.port=8080
      - server.address=0.0.0.0
    depends_on:
      - mysql_user_db
    restart: on-failure

  mysql_user_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=user_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_user_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  friendship-management:
    build: ./FriendshipManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_friendship_db:3306/friendship_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
      - server.port=8080
      - server.address=0.0.0.0
    depends_on:
      - mysql_friendship_db
    restart: on-failure

  mysql_friendship_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=friendship_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_friendship_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  shared-payment-management:
    build: ./PaymentManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_payment_db:3306/payment_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
    depends_on:
      - mysql_shared_payment_db
    restart: on-failure

  mysql_shared_payment_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=shared_payment_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_shared_payments_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5

  account-balance-management:
    build: ./AccountBalanceManagement
    environment:
      - spring.datasource.url=jdbc:mysql://mysql_balance_db:3306/balance_management?serverTimezone=UTC
      - spring.datasource.username=root
      - spring.datasource.password=toor
      - server.port=8080
      - server.address=0.0.0.0
    depends_on:
      - mysql_account_balance_db
    restart: on-failure

  mysql_account_balance_db:
    image: mysql:8.0.33
    environment:
      - 'MYSQL_DATABASE=account_balance_management'
      - 'MYSQL_ROOT_PASSWORD=toor'
    volumes:
      - mysql_account_balance_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
  
volumes:
  mysql_user_data:
  mysql_friendship_data:
  mysql_shared_payments_data:
  mysql_account_balance_data:
